### PR TITLE
Add support for Talos OS

### PR DESCRIPTION
**Pull request by gerhard**
`/etc` on Talos OS is read-only, which means that new PVs will fail to create.

This change makes the hard-coded `/etc/lvm` configurable via the `--hostwritepath` flag.

This is a requirement for:
- https://github.com/metal-stack/helm-charts/pull/64

---

⚠️ This also changes the current `/run/lock/lvm` to `/etc/lvm/lock`

### CODE REVIEW

**Comment by gerhard** [comment]
Given the following local diff:

```diff
diff --git a/tests/bats/test.bats b/tests/bats/test.bats
index 6f4d684..bc4e003 100644
--- a/tests/bats/test.bats
+++ b/tests/bats/test.bats
@@ -1,7 +1,7 @@
 #!/usr/bin/env bats -p

 @test "deploy csi-lvm-controller" {
-    run helm upgrade --install --repo ${HELM_REPO} csi-driver-lvm csi-driver-lvm --values values.yaml --wait --timeout=120s
+    run helm upgrade --install csi-driver-lvm helm-charts/charts/csi-driver-lvm --values values.yaml --wait --timeout=120s
     [ "$status" -eq 0 ]
 }

diff --git a/tests/values.yaml b/tests/values.yaml
index e9703d7..2888828 100644
--- a/tests/values.yaml
+++ b/tests/values.yaml
@@ -11,3 +11,4 @@ provisionerImage:

 lvm:
   devicePattern: /dev/loop100,/dev/loop101
+  hostWritePath: /var/etc/lvm
```

Given a local `tests/helm-charts` repo with my changes from https://github.com/metal-stack/helm-charts/pull/64, `make test` passed locally:

image

FWIW, the first integration test run failed 👇 - flaky test I am assuming - but the second one passed 👆. I refactored all tests to not use hard-coded sleeps, test a single thing, and leverage `kubectl wait --for=jsonpath<CONDITION> --timeout=10s` as much as possible. 

image

Next, I am going to deploy all these changes in my Talos OS cluster and check that PVs are now created as expected. That will be the test that matters the most to me.

I am unable to check if the GitHub workflow still works. Will need one of the maintainers to approve this PR before it runs.

Is there anything that needs to change before this gets merged?

---

After this goes in, I can finish https://github.com/metal-stack/helm-charts/pull/64.

**Review by majst01 — APPROVED** [review]

**Comment by gerhard** [comment]
Thanks for the approve @majst01! I improved the commit messages, all code changes remained the same.

Just waiting for your 👀 & 👍 @mwennrich now.

**Comment by gerhard** [comment]
WDYT @mwennrich ?

**Review by mwennrich — APPROVED** [review]
LGTM

**Comment by jleeh** [comment]
Thanks for making this change @gerhard. I just wanted to use this on a talos cluster and hit the issue, stumbled across this PR. Can confirm both your chart and this change is working for me on our cluster also.

**Comment by gerhard** [comment]
So glad that this helped @jleeh.

Thanks for the 👍 @mwennrich. Can this be merged now & a new release cut?

Once that is done, I can finish https://github.com/metal-stack/csi-driver-lvm/issues/86 so that a new chart version can be made available.

FWIW, I have deployed this into production last weekend. So far, so good 🤞
Screenshot 2023-04-28 at 07 18 00

**Comment by gerhard** [comment]
⭐️⭐️⭐️⭐️⭐️ @majst01

**Comment by Gerrit91** [comment]
Awesome additions! Thank you!

**Pull request merged**
