### PR TITLE
add snapshot feature

### PR DESCRIPTION
**Pull request by mwennrich**
* add snapshot feature
* change some parameters from constant to configurable
* add chart release workflow
* rename charts directory

### CODE REVIEW

**Comment by mwennrich** [comment]
```
ok 1 prepare test files
ok 2 deploy csi-lvm-controller
ok 3 deploy minio
ok 4 deploy inline pod with ephemeral volume
ok 5 inline pod running
ok 6 delete inline linear pod
ok 7 create pvc
ok 8 deploy linear pod
ok 9 deploy block pod
ok 10 linear pvc bound
ok 11 linear pod running
ok 12 block pvc bound
ok 13 block pod running
ok 14 resize volume requests
ok 15 check new linear volume size
ok 16 check new block volume size
ok 17 create snapshot
ok 18 delete linear pod
ok 19 delete block pod
ok 20 delete pvc
ok 21 restore pvc from snapshot
ok 22 deploy linear pod again
ok 23 linear pvc from snapshot bound
ok 24 linear pod running again
ok 25 delete linear pod again
ok 26 delete restored pvc
ok 27 delete snapshot
ok 28 clean up 
```

**Comment by mwennrich** [comment]
chart will move to https://github.com/metal-stack/helm-charts

This will require some rework of integration tests.

**Comment by mwennrich** [comment]
closing in favour of https://github.com/metal-stack/csi-driver-lvm/pull/33

**Comment by majst01** [comment]
Why closing ?

**Pull request closed without merging**
